# Generated by Django 4.2.8 on 2023-12-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="profile",
            name="not_to_Display_Full_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
